#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0

build() {
    add_module overlay
    add_binary bash
    add_binary xargs
    add_binary find
    add_binary grep
    add_binary findmnt
    add_binary uname
    add_binary chroot
    add_runscript
}

help() {
    cat <<HELPEOF
This hook handles system updates and overlays. No
configuration is needed.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
